version: "3"
services:
  besu:
    image: hyperledger/besu:20.10.3
    container_name: besu
    environment:
      - BESU_P2P_HOST=${BESU_P2P_HOST}
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545
    # uncomment if you enable ws and metrics
    #  - 9545:9545
    #  - 8546:8546
    volumes:
      - ./config/besu:/config/besu/
      - ./keys/besu/key:/opt/besu/keys/key
      - ./besu-backup:/opt/besu/data/
    command: ["--config-file=/config/besu/config.toml"]
